apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redis
  namespace: database
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: "20.0.2" 
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: database
      interval: 12h
  values: 
