apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "2.9.3"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
      interval: 60m
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    promtail:
      enabled: true
    loki:
      enabled: true
      isDefault: true
      serviceMonitor:
        enabled: true
        additionalLabels:
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h