apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
  deploymentMode: SingleBinary
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    schemaConfig:
      configs:
        - from: 2024-06-01
          object_store: filesystem
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  singleBinary:
    replicas: 1 


    monitoring:
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
      dashboards:
        enabled: false
      rules:
        enabled: false
        alerting: false