apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: open-webui
      version: 4.1.0.
      sourceRef:
        kind: HelmRepository
        name: open-webui
  # https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - http://ollama.ollama:11434
    extraEnvVars:
#      - name: OPENAI_API_KEY
#        value:
