---
apiVersion: v1
kind: Namespace
metadata:
  name: ownapps
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: ownapps
spec:
  interval: 1h
  url: https://open-webui.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ownapps
spec:
  releaseName: open-webui
  interval: 10m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: ownapps
      version: 3.1.1
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ollama:
      enabled: true
    extraEnvVars:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-api-key
          key: api-key
