---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 1h
  url: https://helm.openwebui.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  releaseName: open-webui
  interval: 10m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
      version: 4.1.0
  values:
    ollama:
      enabled: false
    # extraEnvVars:
    # - name: OPENAI_API_KEY
    #   valueFrom:
    #     secretKeyRef:
    #       name: openai-api-key
    #       key: api-key
  
