---
apiVersion: v1
kind: Namespace
metadata:
  name: ownapps
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: ownapps
spec:
  interval: 1h
  url: https://open-webui.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ownapps
spec:
  releaseName: open-webui
  interval: 10m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: ownapps
      version: 3.0.10
  values:
    ollama:
      enabled: false
    nodeSelector:
      disktype: ssd
    persistence:
      enabled: true
      size: 15Gi
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
    extraEnvVars:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-api-key
          key: api-key
