apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/remediation: enabled
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.3.1
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
