---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana 
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "8.3.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    adminPassword: strongpassword
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - hosts:
            - grafana.yuandrk.net
          secretName: grafana-ingress-prod
      hosts:
        - grafana.yuandrk.net
    persistence:
      enabled: true
      type: pvc
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    sidecar:
      datasources: 
        enabled: true
        label: grafana_datasource
        lebelValue: "1"
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/default
            foldersFromFilesStructure: false
    extraVolumeMounts:
      - name: collection
        mountPath: /var/lib/grafana/dashboards/default
        readOnly: true
    extraVolume:
      volumes:
        - name: collection
          emptyDir:
            sizeLimit: 500Mi  
        