apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana.yaml
  - weave-gitops-dashboard.yaml
  - kube-prometheus-stack-release.yaml
  - kube-prometheus-stack-repository.yaml

configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml