---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: "25.22.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    # grafana:
    #   ingress:
    #     enabled: true
    #     ingressClassName: traefik
    #     annotations:
    #       cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    #     tls:
    #       - hosts:
    #           - grafana.yuandrk.net
    #         secretName: grafana-ingress-prod
    #     hosts:
    #       - grafana.yuandrk.net