---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/issuer: "letsencrypt-prod" 
        tls:
          - hosts:
              - grafana.yuandrk.net
            secretName: grafana-ingress-qgwrl
        hosts:
          - grafana.yuandrk.net