---
apiVersion: v1
kind: Namespace
metadata:
  name: openweb
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: openweb
spec:
  interval: 1h
  url: https://open-webui.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: openweb
spec:
  releaseName: open-webui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: openweb
      version: 3.0.5
  values:
    ollama:
      enabled: true
      fullnameOverride: "open-webui-ollama"
    nodeSelector:
      kubernetes.io/arch: amd64
