
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homepage
  namespace: ownapps
spec:
  interval: 24h
  url: https://jameswynn.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: ownapps
      interval: 1m0s
  