---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ownapps
  namespace: ownapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi