apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-finance
  namespace: ownapps
spec:
  accessModes:
    -  ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi