apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: ownapps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-storage
  resources:
    requests:
      storage: 500Gi