---
apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "15.5.16" 
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: database
      interval: 12h
  values: 
    primary:
      persistence:
        enabled: true
        existingClaim: database
    volumePermissions:
      enabled: true
      

