
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: it-tools
  namespace: ownapps
spec:
  interval: 24h
  type: oci
  url: oci://tccr.io/truecharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: ownapps
spec:
  chart:
    spec:
      chart: it-tools
      sourceRef:
        kind: HelmRepository
        name: it-tools
        namespace: ownapps
