
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: finance
  namespace: ownapps
spec:
  interval: 24h
  url: https://beluga-cloud.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: finance
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: actual
      sourceRef:
        kind: HelmRepository
        name: finance
        namespace: ownapps
      interval: 1m0s
  