apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
Data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus-from-code 
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/ 
      # access: proxy
      isDefault: true
      jsonData:
        timeInterval: "30s"
        httpMethod: POST
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://kube-prometheus-stack-alertmanager.monitoring:9093/ 
      # access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
