apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: ownapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9091
            - containerPort: 51413
            - containerPort: 51413
              protocol: UDP
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: config
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: media
              mountPath: /watch
              subPath: watch
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: media
          persistentVolumeClaim:  
          claimName: media-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9091
      targetPort: 9091
    - name: peer-tcp
      port: 51413
      targetPort: 51413
      protocol: TCP
    - name: peer-udp
      port: 51413
      targetPort: 51413
      protocol: UDP
  selector:
    app: transmission
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: ownapps
spec:
  type: NodePort
  selector:
    app: transmission
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
      nodePort: 30080