apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: transmission
  namespace: ownapps
spec:
  interval: 24h
  url: https://k8s-at-home.com/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: transmission
      sourceRef:
        kind: HelmRepository
        name: transmission 
        namespace: ownapps
      interval: 1m0s
  values: 
    global:
      # Ensure the global settings are compatible
      nameOverride: transmission
    persistence:    
      config:
        enabled: true
        type: pvc
        mountPath: /config
        existingClaim: shared-pvc 

      downloads:
        enabled: true
        type: pvc
        mountPath: /downloads
        existingClaim: shared-pvc 

      watch:
        enabled: true
        type: pvc
        mountPath: /watch
        existingClaim: shared-pvc 