apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: transmission
  namespace: ownapps
spec:
  interval: 24h
  url: https://k8s-at-home.com/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: transmission
      sourceRef:
        kind: HelmRepository
        name: transmission 
        namespace: ownapps
      interval: 1m0s
  values: 
    securityContext:
      runAsUser: 1000  # Replace with actual UID
      runAsGroup: 1000  # Replace with actual GID
      fsGroup: 1000  # Replace with actual GID
    
    config:
      enabled: true
      mountPath: /config
      existingClaim: shared-pvc 

    downloads:
      enabled: true
      mountPath: /downloads
      existingClaim: shared-pvc 

    watch:
      enabled: true
      mountPath: /watch
      existingClaim: shared-pvc 