apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: transmission
  namespace: ownapps
spec:
  interval: 24h
  url: https://k8s-at-home.com/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: transmission
      sourceRef:
        kind: HelmRepository
        name: transmission 
        namespace: ownapps
      interval: 1m0s
  # values:  # https://github.com/utkuozdemir/helm-charts/blob/master/jellyfin/values.yaml
  #   persistence:
  #     enabled: true
  #     existingClaim: shared-pvc 