apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: ownapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: TRANSMISSION_WEB_HOME
              value: "" #optional
            - name: USER
              value: "" #optional
            - name: PASS
              value: "" #optional
            - name: WHITELIST
              value: "" #optional
            - name: PEERPORT
              value: "" #optional
            - name: HOST_WHITELIST
              value: "" #optional
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: watch
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: ownapps
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
    - protocol: TCP
      port: 51413
      targetPort: 51413
    - protocol: UDP
      port: 51413
      targetPort: 51413