apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin
  namespace: ownapps
spec:
  interval: 24h
  url: https://utkuozdemir.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: ownapps
      interval: 1m0s
  values:  # https://github.com/utkuozdemir/helm-charts/blob/master/jellyfin/values.yaml
    persistence:
      config:
        enabled: true
        existingClaim: media-pvc
      media:
        enabled: true
        existingClaim: media-pvc
    extraVolumeMounts:
      - name: media-pvc
        mountPath: /downloads
        subPath: downloads
    extraVolumes:
      - name: media-pvc
        persistentVolumeClaim:
          claimName: media-pvc