apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: ownapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: JELLYFIN_PublishedServerUrl
          value: "192.168.0.5"
        ports:
        - containerPort: 8096
          protocol: TCP
        - containerPort: 8920
          protocol: TCP
        - containerPort: 7359
          protocol: UDP
        - containerPort: 1900
          protocol: UDP
        volumeMounts:
        - name: media-pvc
          mountPath: /config
          subPath: config
        - name: media-pvc
          mountPath: /data/movies
          subPath: downloads
      volumes:
      - name: media-pvc
        persistentVolumeClaim:
          claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: ownapps
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
  - protocol: TCP
    port: 8920
    targetPort: 8920
  - protocol: UDP
    port: 7359
    targetPort: 7359
  - protocol: UDP
    port: 1900
    targetPort: 1900
  type: NodePort