apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: ownapps
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: ownapps
      interval: 1m0s
  values:  # https://github.com/utkuozdemir/helm-charts/blob/master/jellyfin/values.yaml
    persistence:
      config:
        enabled: true
        existingClaim: media-pvc
        subPath: config
      data:
        enabled: true
        existingClaim: media-pvc
        subPath: downloads
    extraVolumeMounts:
      - name: media-pvc
        mountPath: /watch
        subPath: watch
    extraVolumes:
      - name: media-pvc
        persistentVolumeClaim:
          claimName: media-pvc