apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
  namespace: ownapps 
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: ownapps
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.15.7" 
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: ownapps