apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: zekker6
  namespace: ownapps  # Change this to the desired namespace
spec:
  interval: 1h
  url: https://zekker6.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb
  namespace: ownapps
spec:
  interval: 1h
  chart:
    spec:
      chart: nocodb
      version: "0.38.0" 
      sourceRef:
        kind: HelmRepository
        name: zekker6
        namespace: ownapps