
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: my-nocodb
  namespace: ownapps
spec:
  interval: 24h
  url: https://zekker6.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-nocodb
  namespace: ownapps
spec:
  chart:
    spec:
      chart: nocodb
      version: 0.38.0
      sourceRef:
        kind: HelmRepository
        name: my-nocodb
        namespace: ownapps
